AWSTemplateFormatVersion: 2010-09-09
Description: Qiita
Parameters:
  PjName:
    Type: String
    Default: Qiita
Resources:
  QiitaRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: !Sub "${PjName} CodeCommit Repositroy"
      RepositoryName: !Sub "${PjName}"
      Tags:
        - Key: Name
          Value: !Sub "${PjName}"

Outputs:
  CodeCommitRepositoryName:
    Value: !GetAtt "QiitaRepository.Name"
    Export:
      Name: CodeRepositoryName
  CodeCommitRepositoryArn:
    Value: !GetAtt QiitaRepository.Arn
    Export:
      Name: CodeRepositoryArn
  CodeCommitRepositoryUrl:
    Value: !GetAtt QiitaRepository.CloneUrlHttp
    Export:
      Name: CodeRepositoryUrl
