AWSTemplateFormatVersion: 2010-09-09
Description: Qiita
Parameters:
  PjName:
    Type: String
    Default: Qiita
Resources:
  # CodeBuild
  QiitaCodeBuildPj:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: CodeBuild
      Environment:
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: AWS_DOMAIN
            Type: PLAINTEXT
            Value: !Sub "${PjName}"
          - Name: CODEARTIFACT_URL
            Value: "https://$AWS_DOMAIN-$AWS_ACCOUNT_ID.d.codeartifact.$AWS_DEFAULT_REGION.amazonaws.com/npm/cicd/"

        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      Name: !Sub "${PjName}"
      ServiceRole: !ImportValue QiitaCodeBuildRoleName
      Source:
        BuildSpec: buildspec.yml
        Type: CODEPIPELINE
      Tags:
        - Key: Name
          Value: Qiita
  # CloudWatch Logs
  QiitaCloudWatchLogs:
    Type: "AWS::Logs::LogGroup"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub "${PjName}"
      RetentionInDays: 60
      Tags:
        - Key: Name
          Value: !Sub "${PjName}"

Outputs:
  CodeBuildPj:
    Value: !Ref QiitaCodeBuildPj
    Export:
      Name: QiitaCodeBuildPj