AWSTemplateFormatVersion: 2010-09-09
Description: Create IAM User
Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: amplify-user
      ManagedPolicyArns: ["arn:aws:iam::aws:policy/AdministratorAccess-Amplify"]
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref IAMUser

Outputs:
  IAMUserName:
    Value: !Ref IAMUser
    Export:
      Name: AmplifyUser
  AccessKeyId:
    Value: !Ref AccessKey
  SecretAccessKey:
    Value: !GetAtt AccessKey.SecretAccessKey