AWSTemplateFormatVersion: 2010-09-09
Description: image_dev
Parameters:
  PjName:
    Type: String
    Default: ImageDev
Resources:
  ImageDevRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: !Sub "${PjName} CodeCommit Repositroy"
      RepositoryName: !Sub "${PjName}"
      Tags:
        - Key: Name
          Value: !Sub "${PjName}"

Outputs:
  CodeCommitRepositoryName:
    Value: !GetAtt "ImageDevRepository.Name"
    Export:
      Name: CodeRepositoryName
  CodeCommitRepositoryArn:
    Value: !GetAtt ImageDevRepository.Arn
    Export:
      Name: CodeRepositoryArn
  CodeCommitRepositoryUrl:
    Value: !GetAtt ImageDevRepository.CloneUrlHttp
    Export:
      Name: CodeRepositoryUrl